---
title: Quick Process
---
flowchart TD
    start([Start])
    step_1[Start Process]
    step_2[Analyze Data]
    step_3[Generate Report]
    step_4[End Process]
    end([End])
    start --> step_1
    step_1 --> step_2
    step_2 --> step_3
    step_3 --> step_4
    step_4 --> end